Kernel: Remove __dso_handle and __cxa_atexit()
Defining __cxa_atexit() and declaring __dso_handle doesn't seem to be
necessary anymore. Nothing in the kernel should use static destructors.

Previously, causing a static destructor to be called failed to link with
"hidden symbol `__dso_handle' isn't defined".
Now you additionally get this error:
"undefined reference to `__cxa_atexit".