Toolchain: Update EDK II to edk2-stable202605
The old version failed to build with

"StringFuncs.c:113:15: error: variable ‘Item’ set but not used
 [-Werror=unused-but-set-variable=]"

on my system.

The "GCC5" toolchain tag was deprecated in favor of "GCC", so we need
to replace references to "GCC5" with "GCC".