Toolchain: Fix nix shell prettier package
As of NixOS 26.05:

> error: nodePackages has been removed. Many packages are now available
> at the top level (e.g. `pkgs.package-name`). Check on
> https://search.nixos.org to see if the package is still available.

See: https://github.com/NixOS/nixpkgs/pull/496365