SSHServer: Log incoming service request
Or at least try to, because without decryption support we can't read
the packet.

We now log:
Client protocol string: SSH-2.0-OpenSSH_10.0p2 Ubuntu-5ubuntu5.1
KEXINIT message sent
KEX_ECDH_REPLY message sent
Received packet type: 21
error: Expected packet of type SERVICE_REQUEST

(The 21 here is encrypted data)